version: '3'

services:
  mongo:
    hostname: mongo_database
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: brutal
      MONGODB_USERNAME: freeman
      MONGODB_PASSWORD: brutal
      MONGODB_DATABASE: freeman
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/var/micro-data/mongodb/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_MONGODB_SERVER=mongo
      #      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_PORT=27017
      #      - ME_CONFIG_MONGODB_AUTH_DATABASE=CrownJewels
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=brutal
      - ME_CONFIG_BASICAUTH_USERNAME=freeman
      - ME_CONFIG_BASICAUTH_PASSWORD=brutal
    volumes:
      - ./data/db:/var/micro-data/mongodb/data/db
    links:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
